Docs index
beyondstorage/site pull request #212
Opened 2021-08-31 01:53 UTC by tt-haogege

Modify site docs projects #180

2021-08-31 08:41 UTC, zhangdichn requested changes

2021-08-31 08:41 UTC, zhangdichn commented on docusaurus.config.js
>              {
这里不能注释掉，需求是现有的六个项目需要按照 ui 上的 card style 来显示

2021-08-31 08:41 UTC, zhangdichn commented on docusaurus.config.js
> +                description: 'A vendor-neutral storage library for Golang: Write once, run on every storage service.'
description 字段可以通过 githu API 获取

2021-08-31 08:41 UTC, zhangdichn commented on src/pages/docs.js
> +        version = '0.1.0',
项目的最新版本和发布日期也可以通过 github API 获取

2021-08-31 08:41 UTC, zhangdichn commented on src/pages/styles.module.css
> +  background-image: url("/img/underline.svg");
这里为为什么要改成双引号

2021-08-31 08:43 UTC, tt-haogege commented on src/pages/styles.module.css
> +  background-image: url("/img/underline.svg");
应该是格式化的时候干的

2021-08-31 09:23 UTC, Xuanwo commented on docusaurus.config.js
>              {
嗯，未来还会新增其他项目

2021-09-01 08:20 UTC, Xuanwo commented on src/pages/docs.js
> +                <p>Under Development</p>
Maybe we need to remove this line?

2021-09-01 09:15 UTC, tt-haogege commented on src/pages/docs.js
> +                <p>Under Development</p>
Fine

2021-09-03 07:58 UTC, closed without merging